name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build with Buildozer
      uses: artem-sobolev/action-buildozer@v1
      with:
        buildozer_version: stable
        work_dir: ./
        args: android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: veta-apk
        path: bin/*.apk
